import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Check, X, ArrowRight, Sparkles } from "lucide-react";

const competitors: Record<string, {
  name: string;
  tagline: string;
  price: string;
  ourAdvantages: string[];
  theirAdvantages: string[];
  features: { name: string; sproutcraft: boolean | string; competitor: boolean | string }[];
  faqs: { q: string; a: string }[];
}> = {
  "emergent": {
    name: "Emergent.sh",
    tagline: "AI-powered full-stack development platform",
    price: "~$30/mo",
    ourAdvantages: [
      "3x more daily generations on free tier",
      "No credit card required to start",
      "More transparent pricing",
      "Faster generation times",
      "Better mobile-responsive output",
      "More template variety",
    ],
    theirAdvantages: [
      "Established brand recognition",
      "Multi-agent architecture",
      "Autonomous debugging system",
    ],
    features: [
      { name: "Free tier available", sproutcraft: "3 generations/day", competitor: "Limited" },
      { name: "Code ownership", sproutcraft: "100% yours", competitor: "100% yours" },
      { name: "GitHub export", sproutcraft: true, competitor: true },
      { name: "Custom domains", sproutcraft: true, competitor: true },
      { name: "Database included", sproutcraft: true, competitor: true },
      { name: "Auth included", sproutcraft: true, competitor: true },
      { name: "API access", sproutcraft: "Pro+", competitor: "Varies" },
      { name: "Team collaboration", sproutcraft: "Business", competitor: "Limited" },
    ],
    faqs: [
      { q: "Is SproutCraft better than Emergent.sh?", a: "SproutCraft offers more daily generations on the free tier, faster processing, and more transparent pricing. We focus on delivering the best value with no hidden costs." },
      { q: "Can I export my code from SproutCraft?", a: "Yes! You own 100% of the code generated by SproutCraft. Export anytime with no restrictions." },
      { q: "What tech stack does SproutCraft generate?", a: "We generate modern React/Next.js applications with TypeScript and Tailwind CSS." },
    ],
  },
  "lovable": {
    name: "Lovable",
    tagline: "Build production-ready software with AI",
    price: "$25-100/mo",
    ourAdvantages: [
      "50% lower starting price",
      "No credit card required",
      "True full-stack code ownership",
      "Faster generation speeds",
      "More generous free tier",
      "No vendor lock-in",
    ],
    theirAdvantages: [
      "Larger user base and community",
      "Backed by $330M Series B",
      "Enterprise customers like Klarna",
    ],
    features: [
      { name: "Starting price", sproutcraft: "$0/mo", competitor: "$25/mo" },
      { name: "Free tier generations", sproutcraft: "3/day", competitor: "5/day (limited)" },
      { name: "Code ownership", sproutcraft: "100% yours", competitor: "100% yours" },
      { name: "Export to GitHub", sproutcraft: true, competitor: true },
      { name: "Processing speed", sproutcraft: "4x on Pro", competitor: "Varies" },
      { name: "Project history", sproutcraft: "1 year on Pro", competitor: "90 days" },
    ],
    faqs: [
      { q: "Why choose SproutCraft over Lovable?", a: "SproutCraft offers lower prices with more features. Our Pro plan is half the price of Lovable's while offering unlimited generations and longer project history." },
      { q: "Is the code quality comparable?", a: "Yes, both generate production-ready code. SproutCraft focuses on clean, maintainable code that's easy to customize." },
    ],
  },
  "bolt": {
    name: "Bolt.new",
    tagline: "AI-powered full-stack web development",
    price: "$20/mo",
    ourAdvantages: [
      "Persistent project history",
      "Better mobile output",
      "Real-time collaboration",
      "Advanced template library",
      "Better UX for non-technical users",
      "Comprehensive feature set",
    ],
    theirAdvantages: [
      "Integrated with StackBlitz",
      "Fast initial load times",
      "Good for quick prototypes",
    ],
    features: [
      { name: "Project persistence", sproutcraft: "Always saved", competitor: "Session-based" },
      { name: "Mobile responsiveness", sproutcraft: "Built-in", competitor: "Variable" },
      { name: "Collaboration", sproutcraft: "Real-time", competitor: "Limited" },
      { name: "Templates", sproutcraft: "50+", competitor: "Basic" },
    ],
    faqs: [
      { q: "What makes SproutCraft different from Bolt.new?", a: "SproutCraft saves all your projects permanently and focuses on production-ready output rather than quick prototypes. Our mobile-first approach ensures your apps work everywhere." },
    ],
  },
  "cursor": {
    name: "Cursor",
    tagline: "The AI-powered code editor",
    price: "$20/mo",
    ourAdvantages: [
      "No coding required",
      "Visual interface for everyone",
      "Faster for non-developers",
      "Complete app generation",
      "Works for non-technical founders",
      "Pre-built components and templates",
    ],
    theirAdvantages: [
      "Powerful IDE for developers",
      "Git integration",
      "Debugging tools",
      "Full code control",
    ],
    features: [
      { name: "Coding required", sproutcraft: false, competitor: true },
      { name: "Visual builder", sproutcraft: true, competitor: false },
      { name: "App scaffolding", sproutcraft: "Complete apps", competitor: "Code assistance" },
      { name: "Learning curve", sproutcraft: "Low", competitor: "High" },
    ],
    faqs: [
      { q: "Is SproutCraft a replacement for Cursor?", a: "No - they're different tools for different users. Cursor is for developers who want AI-assisted coding. SproutCraft is for anyone who wants to build apps without coding at all." },
    ],
  },
  "replit": {
    name: "Replit",
    tagline: "Build, share, and ship anything",
    price: "$25/mo",
    ourAdvantages: [
      "Simpler, focused interface",
      "No coding required",
      "Better for non-developers",
      "More templates",
      "Easier onboarding",
      "Focused on app building",
    ],
    theirAdvantages: [
      "Full IDE with debugging",
      "Multi-language support",
      "Larger ecosystem",
      "Ghostwriter code assistant",
    ],
    features: [
      { name: "No-code mode", sproutcraft: true, competitor: false },
      { name: "AI app generation", sproutcraft: "Primary focus", competitor: "Agent mode" },
      { name: "Learning curve", sproutcraft: "Easy", competitor: "Medium" },
      { name: "Deployment", sproutcraft: "One-click", competitor: "Available" },
    ],
    faqs: [
      { q: "Should I use Replit or SproutCraft?", a: "If you want to learn coding, use Replit. If you want to build apps without coding, use SproutCraft." },
    ],
  },
  "windsurf": {
    name: "Windsurf",
    tagline: "AI-powered IDE by Codeium",
    price: "$10-20/mo",
    ourAdvantages: [
      "No coding required",
      "Complete app generation",
      "Better for non-developers",
      "Visual interface",
      "Pre-built templates",
      "Faster time to results",
    ],
    theirAdvantages: [
      "Developer-focused IDE",
      "Good code completion",
      "Context understanding",
      "Works with existing projects",
    ],
    features: [
      { name: "Code generation", sproutcraft: "Complete apps", competitor: "Snippets" },
      { name: "No coding required", sproutcraft: true, competitor: false },
      { name: "Template library", sproutcraft: "50+", competitor: "Limited" },
    ],
    faqs: [
      { q: "What is Windsurf best for?", a: "Windsurf is excellent for developers who want AI assistance while coding. SproutCraft is for anyone who wants to build apps without writing code." },
    ],
  },
};

export default async function ComparisonPage({ params }: { params: Promise<{ competitor: string }> }) {
  const { competitor } = await params;
  const data = competitors[competitor] || competitors["emergent"];

  return (
    <div className="min-h-screen bg-white">
      {/* Hero */}
      <section className="bg-gradient-to-b from-emerald-50 to-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-4">
            SproutCraft vs {data.name}
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Honest comparison: See how SproutCraft stacks up against {data.name}
          </p>
        </div>
      </section>

      {/* Feature Comparison */}
      <section className="py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b">
                  <th className="text-left py-4 px-4 font-semibold">Feature</th>
                  <th className="text-center py-4 px-4 font-semibold bg-emerald-50 text-emerald-700">SproutCraft</th>
                  <th className="text-center py-4 px-4 font-semibold">{data.name}</th>
                </tr>
              </thead>
              <tbody>
                {data.features.map((row, index) => (
                  <tr key={index} className="border-b">
                    <td className="py-4 px-4 text-gray-600">{row.name}</td>
                    <td className="py-4 px-4 text-center bg-emerald-50">
                      {typeof row.sproutcraft === "boolean" ? (
                        row.sproutcraft ? (
                          <Check className="w-5 h-5 text-emerald-600 mx-auto" />
                        ) : (
                          <X className="w-5 h-5 text-gray-300 mx-auto" />
                        )
                      ) : (
                        <span className="text-sm font-medium text-emerald-700">{row.sproutcraft}</span>
                      )}
                    </td>
                    <td className="py-4 px-4 text-center">
                      {typeof row.competitor === "boolean" ? (
                        row.competitor ? (
                          <Check className="w-5 h-5 text-gray-400 mx-auto" />
                        ) : (
                          <X className="w-5 h-5 text-gray-300 mx-auto" />
                        )
                      ) : (
                        <span className="text-sm text-gray-600">{row.competitor}</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Advantages */}
      <section className="py-16 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-2 gap-12">
            {/* Where We Win */}
            <Card className="border-emerald-200">
              <CardContent className="p-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-2">
                  <Sparkles className="w-6 h-6 text-emerald-500" />
                  Where SproutCraft Wins
                </h2>
                <ul className="space-y-4">
                  {data.ourAdvantages.map((adv, index) => (
                    <li key={index} className="flex items-start gap-3">
                      <Check className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" />
                      <span className="text-gray-600">{adv}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Where They Win */}
            <Card>
              <CardContent className="p-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6">
                  Where {data.name} is Strong
                </h2>
                <ul className="space-y-4">
                  {data.theirAdvantages.map((adv, index) => (
                    <li key={index} className="flex items-start gap-3">
                      <Check className="w-5 h-5 text-gray-400 flex-shrink-0 mt-0.5" />
                      <span className="text-gray-600">{adv}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center mb-12">
            Frequently Asked Questions
          </h2>
          <div className="space-y-6">
            {data.faqs.map((faq, index) => (
              <div key={index} className="border-b pb-6">
                <h3 className="font-semibold text-lg mb-2">{faq.q}</h3>
                <p className="text-gray-600">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-gradient-to-r from-emerald-500 to-teal-500 text-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4">
            Ready to Try SproutCraft?
          </h2>
          <p className="text-xl mb-8 opacity-90">
            Start free, upgrade when you're ready. No pressure.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/signup">
              <Button size="lg" variant="secondary" className="text-emerald-600">
                Get Started Free <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
            <Link href="/pricing">
              <Button size="lg" variant="outline" className="border-white text-white hover:bg-white/20">
                View Pricing
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
